### ISSUE TITLE
process_atac issue

### ISSUE THREAD

**Issue by daramirez** [Dowell-Lab/DAStk#30]
Hi,
I am seeing the following error message when using the process_atac module:

----------------------------------

cat dastk-process_atac.4344096.err

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1173, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('O') to dtype('int64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/3.7.4/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/python/3.7.4/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/dara6367/.local/lib/python3.7/site-packages/DAStk/process_atac.py", line 51, in find_motifs_in_chrom
    names=['chrom', 'start', 'end'], na_filter=False, dtype={'chrom':'str', 'start':'int', 'end':'int'})
  File "/Users/dara6367/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/dara6367/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/Users/dara6367/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/Users/dara6367/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 973, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1179, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: invalid literal for int() with base 10: ''
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dara6367/.local/bin/process_atac", line 10, in <module>
    sys.exit(process_atac())
  File "/Users/dara6367/.local/lib/python3.7/site-packages/DAStk/__init__.py", line 7, in process_atac
    p.main()
  File "/Users/dara6367/.local/lib/python3.7/site-packages/DAStk/process_atac.py", line 259, in main
    [md_score, small_window, large_window, motif_site_count, heat] = get_md_score(filename, int(args.mp_threads), args.atac_peaks_filename, CHROMOSOMES, args.radius)
  File "/Users/dara6367/.local/lib/python3.7/site-packages/DAStk/process_atac.py", line 131, in get_md_score
    CHROMOSOMES)
  File "/opt/python/3.7.4/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/python/3.7.4/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: invalid literal for int() with base 10: ''

------------------------

I have not been able to determine what is causing this error. Please let me know if there is anything else I can provide to troubleshoot this issue.
Thank you!
Daniel

**Comment by ignaciot** [comment]
Just posting the outcome here in case this happens to someone else:

DAStk expects motif files in traditional BED format (tab-separated: chromosome, start, end, etc). One of the motif files had apparently been edited by hand and accidentally had an extra line at the end with the motif name. This was breaking the call to load the BED file as a Pandas dataframe, since it was expecting at least 3 tab-separated columns. 

If you get errors like this (expected "int" and got X) this is likely an issue with the motif file containing non-standard entries.
