### ISSUE TITLE
Error while create MD score file

### ISSUE THREAD

**Issue by HieuNg1598** [Dowell-Lab/DAStk#32]
The problem happened when i tried to compare between groups. Do you have any suggestions or solutions ? Hope to hear from you soon

SP5_MOUSE.H11MO.0.C (-0.010, p-value = 9.99E-07)
TYY1_MOUSE.H11MO.0.A (-0.106, p-value = 1.12E-06)
ELF5_MOUSE.H11MO.0.A (0.027, p-value = 2.83E-06)
ZFX_MOUSE.H11MO.0.B (-0.045, p-value = 8.19E-06)
MAZ_MOUSE.H11MO.0.A (-0.008, p-value = 1.41E-05)
TAF1_MOUSE.H11MO.0.A (-0.063, p-value = 1.50E-05)
E2F7_MOUSE.H11MO.0.C (-0.046, p-value = 1.60E-05)
ZN281_MOUSE.H11MO.0.A (-0.017, p-value = 1.90E-05)
EGR1_MOUSE.H11MO.0.A (-0.029, p-value = 2.59E-05)
SPI1_MOUSE.H11MO.0.A (0.054, p-value = 2.81E-05)
EGR2_MOUSE.H11MO.0.A (-0.024, p-value = 8.69E-05)
Traceback (most recent call last):
  File "/home/singlecell/miniconda3/bin/differential_md_score", line 8, in <module>
    sys.exit(differential_md_score())
  File "/home/singlecell/miniconda3/lib/python3.9/site-packages/DAStk/__init__.py", line 12, in differential_md_score
    d.main()
  File "/home/singlecell/miniconda3/lib/python3.9/site-packages/DAStk/differential_md_score.py", line 298, in main
    plt.xscale('log',basex=2)
  File "/home/singlecell/miniconda3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 3035, in xscale
    return gca().set_xscale(value, **kwargs)
  File "/home/singlecell/miniconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/home/singlecell/miniconda3/lib/python3.9/site-packages/matplotlib/axis.py", line 816, in _set_axes_scale
    ax._axis_map[name]._set_scale(value, **kwargs)
  File "/home/singlecell/miniconda3/lib/python3.9/site-packages/matplotlib/axis.py", line 773, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "/home/singlecell/miniconda3/lib/python3.9/site-packages/matplotlib/scale.py", line 714, in scale_factory
    return scale_cls(axis, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'basex'

**Comment by ignaciot** [comment]
This sounds like a possible compatibility issue with the matplotlib version you are running. What version are you currently using, if you run `pip freeze`?
