### ISSUE TITLE
OSError: ["Can't find mysql at path mysql", "Can't find path to fetchChromsizes"]

### ISSUE THREAD

**Issue by konradtaube** [Dowell-Lab/DAStk#39]
Hello,

I am trying to run DAStk and am finding an issue with process_atac. When I try the following command:

`process_atac -e 01intersected.bedgraph -m /scratch/avasemag1/taubekon/ATACseq/FASTQ_ATAC_43955/sortedbams/peaks/motifs/01motifs/knownResults -g GCF_010015445.1 -o /scratch/avasemag1/taubekon/ATACseq/FASTQ_ATAC_43955/sortedbams/DAStk`

And then I get the following errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pybedtools/helpers.py", line 896, in chromsizes
    return getattr(genome_registry, genome)
AttributeError: module 'pybedtools.genome_registry' has no attribute 'GCF_010015445.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/avasemag1/taubekon/ATACseq/dastk-1.0.1/bin/process_atac", line 10, in <module>
    sys.exit(process_atac())
  File "/usr/local/lib/python3.10/site-packages/DAStk/__init__.py", line 9, in process_atac
    p.main()
  File "/usr/local/lib/python3.10/site-packages/DAStk/process_atac.py", line 211, in main
    chr_size_file = pybedtools.chromsizes(args.genome)
  File "/usr/local/lib/python3.10/site-packages/pybedtools/helpers.py", line 900, in chromsizes
    return get_chromsizes_from_ucsc(genome)
  File "/usr/local/lib/python3.10/site-packages/pybedtools/helpers.py", line 797, in get_chromsizes_from_ucsc
    raise OSError(failures)
OSError: ["Can't find mysql at path mysql", "Can't find path to fetchChromsizes"]
```

So my guess is that this has something to do with an issue with my genome file. I got my genome file `-g GCF_010015445.1` from the UCSC site:

<img width="1070" alt="Screen Shot 2024-02-05 at 4 09 32 PM" src="https://github.com/Dowell-Lab/DAStk/assets/54451086/1855c0f6-7c37-455c-8cf1-ad7167d7f1da">

But perhaps there is a step I am missing before I can use this? My bedgraph file looks something like this: 

`head 01intersected.bedgraph
track type=bedGraph
CM020909.1	74576	74578	1
CM020909.1	74578	74580	2
CM020909.1	74580	74585	8
CM020909.1	74585	74587	10
CM020909.1	74587	74588	13
CM020909.1	74588	74590	14
CM020909.1	74590	74592	15
CM020909.1	74592	74594	17
CM020909.1	74594	74595	19`

Thank you in advance!

**Comment by ignaciot** [comment]
Hey there,

Sorry it took a bit to get back. It looks like the helper code to retrieve the chromosome sizes is expecting the mysql command-line client to be installed. If you haven't already, could you test this and let us know if the issue persists?

You can find instructions to install the mysql client for your platform [here](https://dev.mysql.com/doc/mysql-getting-started/en/#mysql-getting-started-installing). Also make sure [the command-line client executable is in your system path](https://stackoverflow.com/questions/5920136/mysql-is-not-recognised-as-an-internal-or-external-command-operable-program-or-b). Next time feel free to nudge if you haven't heard back earlier!
